/*
Conversion Header file
Kraisorn Liansee
*/

/*--------------------------------------------*/
/*       This module defines some data        */
/*       required for converting 90 cols      */
/*       CU-Writer (V1.10 on Hercules) into   */
/*       80 cols (V1.2 Hercules/EGA/VGA)      */
/*--------------------------------------------*/

#ifndef CONVERT_H_INCLUDED
#define CONVERT_H_INCLUDED

#define SHRINK_FACTOR   10           /* Columns decreased    */
#define CENTER_FACTOR    5           /* Shifting left factor */

#endif
