#include <stdio.h>
#include <stdlib.h>
#include <conio.h>
#include <dos.h>
#include <string.h>
#include <dir.h>
#include <bios.h>
#include <fcntl.h>
#include <sys\stat.h>
#include <process.h>
#include <ctype.h>
#include <errno.h>

#include "..\common\kbdcode.h"
#include "..\common\const.h"
#include "..\common\cwtype.h"

#include "..\common\cscrn.h"
#include "..\common\sound.h"
#include "..\common\cusong.h"
#include "..\common\dir.h"
#include "..\common\ekbd.h"
#include "..\common\grphc.h"

#include "const.h"
#include "var.h"
