/* inc.h use in ..\scup only
Written Suttipong Kanakakorn
Mon  08-07-1989  00:26:41
*/

#include "..\common\cwtype.h"
#include "..\common\const.h"
#include "..\common\cscrn.h"
#include "..\common\cwgrphc.h"
#include "..\common\dir.h"
#include "..\common\ekbd.h"
#include "..\common\fileutil.h"
#include "..\common\grphc.h"
#include "..\common\kbdcode.h"

#include "const.h"
#include "cuptype.h"
#include "proto.h"
#include "funcmac.h"
