/*
* ============================================================================
* Common MACRO for cw.exe and cuprint.exe
*
* Updated: Suttipong Kanakakorn
*          Sun  08-06-1989  10:04:26
* ============================================================================
*/

#ifndef COMMON_CONST_H_INCLUDED
#define COMMON_CONST_H_INCLUDED

#define BLANK ' '

#define HUNAKADMITO 0xdb  /* treat as upper level */

#endif /* COMMON_CONST_H_INCLUDED */
